### ISSUE TITLE
a question in train_coh.py

### ISSUE THREAD

**Issue by git97shunxin** [subhayanmukherjee/cnninsar#1]
when I read the function "generate_data"(raw 142 in the code) in train_coh.py, I find "while 1:" is used in the function,it seems like a endless loop,and when i run the "train_coh.py",it seems to have really entered an endless loop,I will be grateful if you can answer my question

**Comment by subhayanmukherjee** [comment]
Hello @git97shunxin, Thanks for your question. Actually generate_data() is a generator function that should keep generating batches of training examples of the form <datum, label> and return them to the model training function fit_generator() via the yield() call. You can refer to the Keras documentation, or [this](https://www.pyimagesearch.com/2018/12/24/how-to-use-keras-fit-and-fit_generator-a-hands-on-tutorial/) useful tutorial ( scroll down to the sentence "As the name suggests, the .fit_generator  function assumes there is an underlying function that is generating the data for it." and continue reading )
